/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.tools.activemq.server;

import org.junit.Test;

public class ActiveMQServerTest {
  @Test public void test1() {
    // do nothing for now
  }
}
